apiVersion: v1
kind: Service
metadata:
  name: musician-app
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: musician-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
