name: Deploy to EKS with Helm

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_URI: 474668397798.dkr.ecr.us-east-1.amazonaws.com/musician-app
  EKS_CLUSTER_NAME: musician-app-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update Kubeconfig for EKS
      run: |
        aws eks update-kubeconfig \
          --region ${{ env.AWS_REGION }} \
          --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Verify Kube Access
      run: kubectl get nodes

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Deploy with Helm
      run: |
        helm upgrade --install musician-app ./helm-chart \
          --set image.repository=${{ env.ECR_URI }} \
          --set image.tag=latest \
          --namespace default \
          --create-namespace
